/**
 * Modern SaaS route slugs
 *
 * Routes commonly used by SaaS applications for workspaces, organizations,
 * subscriptions, billing tiers, integrations, and team management.
 */
export const saasSlugs = [
	'automation',
	'automations',
	'bundle',
	'bundles',
	'downgrade',
	'enterprise',
	'feature-flag',
	'feature-flags',
	'integration',
	'integrations',
	'marketplace',
	'onboarding',
	'org',
	'organization',
	'organizations',
	'orgs',
	'plan',
	'plans',
	'premium',
	'quota',
	'seat',
	'seats',
	'sla',
	'subscription',
	'subscriptions',
	'team',
	'teams',
	'template',
	'templates',
	'tenant',
	'tenants',
	'tier',
	'tiers',
	'trial',
	'upgrade',
	'workflow',
	'workflows',
	'workspace',
	'workspaces'
] as const
